### ISSUE TITLE
help me retrieve two services tied to my old @opencongress email

### ISSUE THREAD

**Issue by davidmooreppf** [sunlightlabs/opencongress#507]
Hi team, 

My goal is to accomplish the following :: 

From email dave@opencongress.org, confirm to Lighthouse App support to cancel the account opencongress.lighthouseapp.com. (Tim Ball & others can confirm this has been deprecated, not in use since '10-11.) 

From email david@opencongress.org, change my email for the old @open_gov Twitter account for the OpenGovernment.org site to david attttttttt ttt ppolitics.org. 

Labs staff doesn't have to give me control of the email accounts, even for a day, just help me by responding to each of the above tasks. 

Feel free to call if that's easier, Tim & James Turk have my phone number. Thank you, should just take a few minutes. Email me back at email above and we can chat in IRC or Skype.

**Comment by timball** [comment]
howdy! both accounts have been un-suspended and passwds reset . i'm also logged into webmail for those accounts and ready to take action whenever you make something happen . 

--timball

**Comment by davidmooreppf** [comment]
You rule @timball - thx for fast turnaround. Just looped you in w/ Lighthouse support on dave @, and just triggered a pw reset to david @ - which you can please forward to david atttttttt ppolitics.org. Then feel free to close accounts again. Thx.

**Comment by timball** [comment]
i have forwarded you the response emails . lemmie know if you need anything else .

**Comment by timball** [comment]
okay forwarded all the things . lemmie know when you're set and i'll close
all the things .

On Wed, Apr 8, 2015 at 12:10 PM, David Moore <notifications@github.com>
wrote:

> You rule @timball <https://github.com/timball> - thx for fast turnaround.
> Just looped you in w/ Lighthouse support on dave @, and just triggered a pw
> reset to david @ - which you can please forward to david atttttttt
> ppolitics.org. Then feel free to close accounts again. Thx.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sunlightlabs/opencongress/issues/507#issuecomment-90961866>
> .
>



-- 
        GPG key available on pgpkeys.mit.edu
pub  1024D/511FBD54 2001-07-23 Timothy Lu Hu Ball <timball@tux.org>
Key fingerprint = B579 29B0 F6C8 C7AA 3840  E053 FE02 BB97 511F BD54

**Comment by davidmooreppf** [comment]
All set! Thanks again man, you rock & rule, and do not rot.
